[
uuid(ae55c4c0-64ce-11dd-ad8b-0800200c9a66),
version(1.0),
]
interface DefaultIfName
{

	typedef struct Struct_16_t
	{
		long 	StructMember0;
		short 	StructMember1;
		short 	StructMember2;
		byte 	StructMember3[8];
	}Struct_16_t;

long Proc0(
	[in][string] wchar_t* arg_1, 
	[out]struct Struct_16_t* arg_2);

long Proc1(
	[in][string] wchar_t* arg_1, 
	[in]long arg_2);

long Proc2(
	[in]long arg_1, 
	[in][string] wchar_t* arg_2, 
	[in]long arg_3);

long Proc3(
	[in][unique][string] wchar_t* arg_1, 
	[in][out][ref][range(0,257)] [string] wchar_t* arg_2, 
	[in][out][ref][range(0,257)] [string] wchar_t* arg_3, 
	[in]long arg_4);

long Proc4(
	[in][string] wchar_t* arg_1, 
	[in]long arg_2, 
	[in]long arg_3);

long Proc5(
);

long Proc6(
	[out]long *arg_1, 
	[out]long *arg_2);

long Proc7(
);

long Proc8(
);

long Proc9(
);

long Proc10(
	[out]long *arg_1);

long Proc11(
	[in][string] wchar_t* arg_1);

long Proc12(
	[out]long *arg_1, 
	[out][ref][string] wchar_t** arg_2);
} 